# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [24]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Jamestown,US,42.0970,-79.2353,37.02,97,100,9.22,overcast clouds
1,1,Punta Arenas,CL,-53.1500,-70.9167,37.51,81,40,20.71,scattered clouds
2,2,Norman Wells,CA,65.2820,-126.8329,30.24,93,100,10.36,light snow
3,3,Atuona,PF,-9.8000,-139.0333,76.89,74,4,12.91,clear sky
4,4,Gizo,SB,-8.1030,156.8419,84.97,67,80,6.33,broken clouds
...,...,...,...,...,...,...,...,...,...,...
684,684,Sattahip,TH,12.6664,100.9007,86.99,57,75,4.61,haze
685,685,Lormi,IN,22.2833,81.7333,78.44,49,0,3.04,clear sky
686,686,Verkhnyaya Khava,RU,51.8404,39.9413,39.27,85,100,0.98,overcast clouds
687,687,Beyneu,KZ,45.3167,55.2000,54.07,45,100,19.69,overcast clouds
688,688,Tonkino,RU,57.3726,46.4629,35.89,90,92,4.79,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [4]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Atuona,PF,-9.8000,-139.0333,76.89,74,4,12.91,clear sky
4,4,Gizo,SB,-8.1030,156.8419,84.97,67,80,6.33,broken clouds
5,5,Brazzaville,CG,-4.2658,15.2832,74.57,83,100,4.81,overcast clouds
6,6,Pemangkat,ID,1.1667,108.9667,85.69,65,36,5.84,scattered clouds
7,7,Butaritari,KI,3.0707,172.7902,82.27,67,56,10.63,broken clouds
8,8,Rikitea,PF,-23.1203,-134.9692,71.02,72,100,18.57,overcast clouds
9,9,Grand Gaube,MU,-20.0064,57.6608,74.37,61,60,5.01,broken clouds
10,10,Georgetown,MY,5.4112,100.3354,87.73,72,20,4.61,few clouds
11,11,Avarua,CK,-21.2078,-159.7750,77.05,73,40,12.66,scattered clouds
12,12,Marsa Matruh,EG,31.3525,27.2453,67.78,70,3,2.53,clear sky

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [5]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Atuona,PF,-9.8000,-139.0333,76.89,74,4,12.91,clear sky
4,4,Gizo,SB,-8.1030,156.8419,84.97,67,80,6.33,broken clouds
5,5,Brazzaville,CG,-4.2658,15.2832,74.57,83,100,4.81,overcast clouds
6,6,Pemangkat,ID,1.1667,108.9667,85.69,65,36,5.84,scattered clouds
7,7,Butaritari,KI,3.0707,172.7902,82.27,67,56,10.63,broken clouds
...,...,...,...,...,...,...,...,...,...,...
680,680,Hurghada,EG,27.2574,33.8129,75.24,41,0,9.22,clear sky
681,681,Dzaoudzi,YT,-12.7887,45.2699,76.89,88,0,3.44,clear sky
682,682,Buraydah,SA,26.3260,43.9750,63.05,14,4,6.67,clear sky
684,684,Sattahip,TH,12.6664,100.9007,86.99,57,75,4.61,haze
685,685,Lormi,IN,22.2833,81.7333,78.44,49,0,3.04,clear sky

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [6]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_travel_cities[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# Display sample data
hotel_df.head(8)

           City Country  Max Temp Current Description      Lat       Lng
3        Atuona      PF     76.89           clear sky  -9.8000 -139.0333
4          Gizo      SB     84.97       broken clouds  -8.1030  156.8419
5   Brazzaville      CG     74.57     overcast clouds  -4.2658   15.2832
6     Pemangkat      ID     85.69    scattered clouds   1.1667  108.9667
7    Butaritari      KI     82.27       broken clouds   3.0707  172.7902
8       Rikitea      PF     71.02     overcast clouds -23.1203 -134.9692
9   Grand Gaube      MU     74.37       broken clouds -20.0064   57.6608
10   Georgetown      MY     87.73          few clouds   5.4112  100.3354

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [7]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(8)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Atuona,PF,76.89,clear sky,-9.8000,-139.0333,
4,Gizo,SB,84.97,broken clouds,-8.1030,156.8419,
5,Brazzaville,CG,74.57,overcast clouds,-4.2658,15.2832,
6,Pemangkat,ID,85.69,scattered clouds,1.1667,108.9667,
7,Butaritari,KI,82.27,broken clouds,3.0707,172.7902,
8,Rikitea,PF,71.02,overcast clouds,-23.1203,-134.9692,
9,Grand Gaube,MU,74.37,broken clouds,-20.0064,57.6608,
10,Georgetown,MY,87.73,few clouds,5.4112,100.3354,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [8]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [25]:
#hotels = requests.get(base_url, params=params).json()
# print(hotels)

{'html_attributions': [], 'next_page_token': 'ARywPALsYVIil8OWK2qOSyES72RPtAmtq3VNF43uJzzliElUjqYROCz5oX4CN9rY8mZuk1nDufvV9JYh-Gph13eXiC08lbt-V-O64Kh9GahMMB1QcbXjXIfjWmtqbhG9_DEHqz-JKrcfueEAPtC7oZ6xTbBvLFbLh8A-lb3UpibnrUFzhiA-TfdhXjLZpdC1s7FyxkVaZaKYuuFYRzFwl546by_TpNSiEYP3phXBwGf7Dey14skt1ogHEsE2zEjvDHDRfXx8sptqnVB50KNIwlTau6fYvJEJddLFEK5weX4Gj2J8lUoghaI9mIy-D6TYU3RVF80YDgJ77ETPicUgzjHEOnjcZJY5QUQgVuyA2DmUdkxG7YR4uCCwWjvTWFj21OfkkndnHLuAicGYRo9kl1NX5qxmiWf77Uu6iemCl4Ayn0nAuagQF8YIBkYw', 'results': [{'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2829004, 'lng': 81.74178119999999}, 'viewport': {'northeast': {'lat': 22.2840860302915, 'lng': 81.74844809999999}, 'southwest': {'lat': 22.28138806970849, 'lng': 81.73955889999999}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'suresh Kumar Porte', 'permanently_closed': True, 'place_id': 'ChIJD5AJTNklKDoRRhq-ni_YojE', 'reference': 'ChIJD5AJTNklKDoRRhq-ni_YojE', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': '7PMR+5P6, Kanchanpur, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2785521, 'lng': 81.70777849999999}, 'viewport': {'northeast': {'lat': 22.2798718802915, 'lng': 81.70912743029149}, 'southwest': {'lat': 22.2771739197085, 'lng': 81.70642946970848}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Ganesh Jaiswal', 'place_id': 'ChIJS671700lKDoRJ7mg92KfZX0', 'reference': 'ChIJS671700lKDoRJ7mg92KfZX0', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': '7PH5+C4C, Mundiyadal, Tulsaghat'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2787282, 'lng': 81.70603299999999}, 'viewport': {'northeast': {'lat': 22.28010173029151, 'lng': 81.7074335302915}, 'southwest': {'lat': 22.2774037697085, 'lng': 81.70473556970849}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Smt Jana Bai Dhruw Niwas', 'opening_hours': {'open_now': False}, 'photos': [{'height': 3120, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106146940635172539114">Gumendra Kumar Dhruw</a>'], 'photo_reference': 'ARywPAL12Zk1rypfNRi5QpKKoeGNrz9EO3X_7X-sS1y0iiwMm6Xe_Jj7GbDLZBbPblaIutZ3RGXt05Z8U47oOvvAsKqYzUyBvnWiTSGSSbR5kqRSk_l8OoBQ53WQmCIT3xYJLIuUMM1nytLhHtdJWdBqWBlCAXNVvWtQOe2IuuqPB7_34g9c', 'width': 4160}], 'place_id': 'ChIJ3b1-PpIlKDoRGy9hmZJxE7Q', 'rating': 4.1, 'reference': 'ChIJ3b1-PpIlKDoRGy9hmZJxE7Q', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 7, 'vicinity': '7PH4+FCV, Mundiyadal, Tulsaghat'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.272625, 'lng': 81.75942859999999}, 'viewport': {'northeast': {'lat': 22.2739213302915, 'lng': 81.7609068802915}, 'southwest': {'lat': 22.2712233697085, 'lng': 81.7582089197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Purnesh Jaiswal Palace, Junapara', 'permanently_closed': True, 'photos': [{'height': 3264, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111948591735902568022">Satish Lahare</a>'], 'photo_reference': 'ARywPALQIYcpN8sbHUwGWPJWB8SODDn_3BXkeOKlJHLPY76320Riw2Bp4xGjklpJhQSh7vXXL6jkVL0JnhcoYmmbX5IFiQF8fpseIr73KLM-HhzyjoZl1v-5pnH2XmUoR-emc69cNVqGrkq04HYr3LH58QwRLUBJukz1LQtyhskkwr3YKHLa', 'width': 2448}], 'place_id': 'ChIJifBr2GAkKDoRA5CvMi-8O7U', 'rating': 5, 'reference': 'ChIJifBr2GAkKDoRA5CvMi-8O7U', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': '7QF5+3Q3, Junapara'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2714876, 'lng': 81.70590059999999}, 'viewport': {'northeast': {'lat': 22.27281943029151, 'lng': 81.7073082802915}, 'southwest': {'lat': 22.2701214697085, 'lng': 81.70461031970848}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Advocate ashok upadhyay', 'permanently_closed': True, 'place_id': 'ChIJzX9PPQklKDoRLJQouBpyRGI', 'reference': 'ChIJzX9PPQklKDoRLJQouBpyRGI', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': '7PC4+H9R, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2724, 'lng': 81.7054}, 'viewport': {'northeast': {'lat': 22.2735860802915, 'lng': 81.7067559802915}, 'southwest': {'lat': 22.2708881197085, 'lng': 81.7040580197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Lormi Guest House', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3120, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113611929003671981333">Rakesh Sahu</a>'], 'photo_reference': 'ARywPALWdUYtyJ5FkK9s6hTddPNiB8eohq6ZUiYPWhFwAISvWtHX09p7KPknJB_oEL7qYjotO7uw3_idZ1Xk3xNpe3p1nkz3luxt6JWL2O56fTL3AbnoHg1ffUgJeyw9XBEhA1JDebexKI3OTwm4aRD7kPw7e-7roTLwiha5QF2SDCybqYOD', 'width': 4160}], 'place_id': 'ChIJ6agao5slKDoRgeLXA4zNVT8', 'rating': 4, 'reference': 'ChIJ6agao5slKDoRgeLXA4zNVT8', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 184, 'vicinity': '7PF3+56F, Bilaspur, SH-10, Kota-Lormi Road, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2729275, 'lng': 81.70303410000001}, 'viewport': {'northeast': {'lat': 22.2742661302915, 'lng': 81.70434108029153}, 'southwest': {'lat': 22.2715681697085, 'lng': 81.7016431197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Akat Nishad Lormi', 'place_id': 'ChIJCweWn-4lKDoR-33bTXSvySc', 'plus_code': {'compound_code': '7PF3+56 Lormi, Chhattisgarh, India', 'global_code': '7MJ37PF3+56'}, 'reference': 'ChIJCweWn-4lKDoR-33bTXSvySc', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'village Kundra Para, lormi post office Lormi pin code 495115 Vard no. 12 Lormi, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2725127, 'lng': 81.7029606}, 'viewport': {'northeast': {'lat': 22.2738626802915, 'lng': 81.7043212802915}, 'southwest': {'lat': 22.2711647197085, 'lng': 81.70162331970849}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'वैष्णव हाउस या white house,', 'place_id': 'ChIJV4MGNo8lKDoRI8S-ufHE-3Q', 'plus_code': {'compound_code': '7PF3+25 Lormi, Chhattisgarh, India', 'global_code': '7MJ37PF3+25'}, 'reference': 'ChIJV4MGNo8lKDoRI8S-ufHE-3Q', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'Ward 14, ढोलगी रोड, Lormi'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2753793, 'lng': 81.7017561}, 'viewport': {'northeast': {'lat': 22.2767186302915, 'lng': 81.7030039302915}, 'southwest': {'lat': 22.2740206697085, 'lng': 81.7003059697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Krishak Mitra and laxmi steels', 'permanently_closed': True, 'photos': [{'height': 2080, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108143668353650235531">Krishak Mitra and laxmi steels</a>'], 'photo_reference': 'ARywPAKtQ8PZZvcJL3Oj7uoLjX9Bu-x1zXoVEU2kN8Jzod8Ew6jyayCKesko1bdmarhloQLoy_UrTMaY1jK-TTPOvfwqeHrVeKY5KyV4WToO_gMBibbq7LIjb_orbC_fgT4NNgTLhxFjPxygqSctHygQfij3Vs8cWA5TVU4v5_SVA4K2TwbZ', 'width': 4608}], 'place_id': 'ChIJSZ4BJ2YlKDoRzlSfgtWbjbk', 'plus_code': {'compound_code': '7PG2+5P Lormi, Chhattisgarh, India', 'global_code': '7MJ37PG2+5P'}, 'reference': 'ChIJSZ4BJ2YlKDoRzlSfgtWbjbk', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'Manglm bhawan, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2753793, 'lng': 81.7017561}, 'viewport': {'northeast': {'lat': 22.2767186302915, 'lng': 81.7030039302915}, 'southwest': {'lat': 22.2740206697085, 'lng': 81.7003059697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'New Yadav Hotal', 'photos': [{'height': 864, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104720654301069183573">New Yadav Hotal</a>'], 'photo_reference': 'ARywPAKdmzZOqdwJ27G3RUWdHwqA-ctSMuO5n985chYaxU-D5tmOzshh5iKTRzTIZpNKediPWt9qbC6EYhm286bqhhaCJxU0x9fjxocASfytmfY7G_XKbTgyo3kfMiSCeVt3FCMjAO1ZuEaG7OtnYkwkPYgR7um9C5XiuarqHuO9KC6BiQzd', 'width': 480}], 'place_id': 'ChIJSfQoLcElKDoRMD3Bamw15aM', 'plus_code': {'compound_code': '7PG2+5P Lormi, Chhattisgarh, India', 'global_code': '7MJ37PG2+5P'}, 'rating': 4, 'reference': 'ChIJSfQoLcElKDoRMD3Bamw15aM', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': 'old bus stend, Lormi'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2753793, 'lng': 81.7017561}, 'viewport': {'northeast': {'lat': 22.2767186302915, 'lng': 81.7030039302915}, 'southwest': {'lat': 22.2740206697085, 'lng': 81.7003059697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Fauwara Chowk Front Of Forest Office Yadav Hotels Lormi', 'permanently_closed': True, 'place_id': 'ChIJCTSnToUlKDoRiMifQG4UoFk', 'rating': 4.5, 'reference': 'ChIJCTSnToUlKDoRiMifQG4UoFk', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 2, 'vicinity': '7PG2+5P2, Lormi'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2753792, 'lng': 81.7017561}, 'viewport': {'northeast': {'lat': 22.2767185302915, 'lng': 81.7030039302915}, 'southwest': {'lat': 22.2740205697085, 'lng': 81.7003059697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Gautiya Talab Jhaphal', 'permanently_closed': True, 'photos': [{'height': 2340, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117954077160161327775">sanjay singh Rajput</a>'], 'photo_reference': 'ARywPAJb3pYtYle_bwAE_7RwafzcmnGQuHKeT0dy_PKqk9ktxUh_mPQiSWIEXKj7rwlL8dDxQi08KFEFl_T9tNlcye6LTwGy3hhfF1e4vfSxBDCTwOZdmPVHnDux7XwFzGwCQ31gdTPZHvdGoctF1UnMp4nqpz7p0eIzVBg8mPRKwxvUD1EV', 'width': 4160}], 'place_id': 'ChIJBzSnToUlKDoRwSgeflskoow', 'plus_code': {'compound_code': '7PG2+5P Jhaphal, Chhattisgarh, India', 'global_code': '7MJ37PG2+5P'}, 'rating': 5, 'reference': 'ChIJBzSnToUlKDoRwSgeflskoow', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': '495115, Mungeli Road, Jhaphal'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2801456, 'lng': 81.7003299}, 'viewport': {'northeast': {'lat': 22.2813254302915, 'lng': 81.7018025302915}, 'southwest': {'lat': 22.2786274697085, 'lng': 81.69910456970848}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Ishwar sahu', 'photos': [{'height': 780, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100255923849222981384">Ishwar sahu</a>'], 'photo_reference': 'ARywPALHhnTIILvDyOeaITUgT3w8xFD7Jcy067JBgcr5mNc04gJ0v7Iv8TDxaTrdI5dHBSN9wj3cn-6V5LUF6Di-kq3trMTCMkOMad7YbkHhQJfMk9v-IGO8rwsKHUVXylffb1qzbhFcTpS5R71kQK640V9C4Qcze4I56zEdXwmrr0NhCxAD', 'width': 1040}], 'place_id': 'ChIJH4Is0SslKDoRbmBcoCSwND0', 'plus_code': {'compound_code': '7PJ2+34 Lormi, Chhattisgarh, India', 'global_code': '7MJ37PJ2+34'}, 'reference': 'ChIJH4Is0SslKDoRbmBcoCSwND0', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'Ishwar sahu, C g, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2785958, 'lng': 81.76614029999999}, 'viewport': {'northeast': {'lat': 22.2799356302915, 'lng': 81.76750238029149}, 'southwest': {'lat': 22.2772376697085, 'lng': 81.76480441970848}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Rajendra home', 'place_id': 'ChIJBXyuDJ8lKDoR1ZZbyYpallU', 'reference': 'ChIJBXyuDJ8lKDoR1ZZbyYpallU', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': '7QH8+CFJ, Junapara'}, {'business_status': 'CLOSED_TEMPORARILY', 'geometry': {'location': {'lat': 22.2745462, 'lng': 81.7012655}, 'viewport': {'northeast': {'lat': 22.2759195302915, 'lng': 81.70261278029149}, 'southwest': {'lat': 22.27322156970849, 'lng': 81.69991481970848}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'TAJ GROUP', 'permanently_closed': True, 'place_id': 'ChIJYZJywgElKDoRvyzZZx_tQe8', 'rating': 5, 'reference': 'ChIJYZJywgElKDoRvyzZZx_tQe8', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 1, 'vicinity': '7PF2+RG6, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2715725, 'lng': 81.7003853}, 'viewport': {'northeast': {'lat': 22.2729203302915, 'lng': 81.70172368029151}, 'southwest': {'lat': 22.2702223697085, 'lng': 81.6990257197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Santoshi Lodge Lormi', 'photos': [{'height': 1920, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103242575753950708790">KISHORE KARWAITI</a>'], 'photo_reference': 'ARywPAJW_MBGEtcFWMl-YMEKJ6QyTcKA7EqZPiCkRQgGf93EG52HlbMFNhwbgvFMAP05xBCi3Ri7FBOntD62LKEMP6-qzSE5pp6V7JYI5iusekoTUluoD-qGRB_QiTaYTZw3mUF-lM0M2g_4oyMu8lx20UMo_a_sladbtOpL_IM-vN7G7uss', 'width': 1080}], 'place_id': 'ChIJ3TMElIQlKDoR79ySX9Qo46A', 'plus_code': {'compound_code': '7PC2+J5 Lormi, Chhattisgarh, India', 'global_code': '7MJ37PC2+J5'}, 'rating': 3.8, 'reference': 'ChIJ3TMElIQlKDoR79ySX9Qo46A', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 20, 'vicinity': 'India'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2709831, 'lng': 81.700486}, 'viewport': {'northeast': {'lat': 22.27232853029151, 'lng': 81.7017893302915}, 'southwest': {'lat': 22.2696305697085, 'lng': 81.6990913697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Ashoka Lodge Lormi', 'photos': [{'height': 720, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112643406484532756821">King Fatehi</a>'], 'photo_reference': 'ARywPALvIGlCfUR-gXGsZvRX8UavbZL0gd96jYI8_Z8gcaaGpJ1dispykiv4scrUaLWEcvIGeI5jb-z8dhGBQYtvrmHbXMQOrlug5f_rG3xkOw6bZMcY65tjIf_-S7d81_b9v2I5W8KEtJjF8OxT9tBy5IxLprUew_rudRPyjxtzqeYDhAxA', 'width': 1280}], 'place_id': 'ChIJOX3yJAklKDoRWErveDrZR-A', 'rating': 3.5, 'reference': 'ChIJOX3yJAklKDoRWErveDrZR-A', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 4, 'vicinity': '7PC2+95X, Kota-Lormi Road, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2705658, 'lng': 81.7005898}, 'viewport': {'northeast': {'lat': 22.2719242302915, 'lng': 81.7019271802915}, 'southwest': {'lat': 22.2692262697085, 'lng': 81.6992292197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Yadav Ji Hotel (bhajan Yadav)', 'place_id': 'ChIJ70Kxn4QlKDoRcOLed3HzbaI', 'rating': 3.4, 'reference': 'ChIJ70Kxn4QlKDoRcOLed3HzbaI', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 5, 'vicinity': '7PC2+66G, Shiv Ghat Road, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2729101, 'lng': 81.6985296}, 'viewport': {'northeast': {'lat': 22.2742591802915, 'lng': 81.6998255302915}, 'southwest': {'lat': 22.2715612197085, 'lng': 81.6971275697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Sita Palace', 'opening_hours': {'open_now': True}, 'photos': [{'height': 1920, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104153370048620448089">Setram Yadav</a>'], 'photo_reference': 'ARywPAKVMqb4835iV3XanSwbGjsCMVbVeE-wOpyDXlxpCHpk24DxUu83b4oXmmtOE8Ns_64g50row3VYSZbTBWKI-ycgmz5yEtFnWeMv5A97-Z9rsOR70YYlfspFEMa8KRGPt4e-4K8jkQWm7mB8vnRqv2fkEJTIZab_exd-EoYWgArRw69d', 'width': 1080}], 'place_id': 'ChIJRb9-ToQlKDoRkKfGlVaJbac', 'rating': 3.6, 'reference': 'ChIJRb9-ToQlKDoRkKfGlVaJbac', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 44, 'vicinity': '7MFX+5C6, Lormi'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 22.2732982, 'lng': 81.698247}, 'viewport': {'northeast': {'lat': 22.2746477802915, 'lng': 81.69968808029151}, 'southwest': {'lat': 22.2719498197085, 'lng': 81.6969901197085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Shree Vaishnav Kunj', 'place_id': 'ChIJ57NkQl4lKDoRw4kdJf2FZO8', 'plus_code': {'compound_code': '7MFX+87 Lormi, Chhattisgarh, India', 'global_code': '7MJ37MFX+87'}, 'rating': 5, 'reference': 'ChIJ57NkQl4lKDoRw4kdJf2FZO8', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 3, 'vicinity': 'Old Busstand, Lormi'}], 'status': 'OK'}

In [26]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
        
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [27]:
# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Atuona,PF,76.89,clear sky,-9.8000,-139.0333,Villa Enata
4,Gizo,SB,84.97,broken clouds,-8.1030,156.8419,
5,Brazzaville,CG,74.57,overcast clouds,-4.2658,15.2832,
6,Pemangkat,ID,85.69,scattered clouds,1.1667,108.9667,Hotel Duyung Permai 2
7,Butaritari,KI,82.27,broken clouds,3.0707,172.7902,Isles Sunset Lodge
8,Rikitea,PF,71.02,overcast clouds,-23.1203,-134.9692,
9,Grand Gaube,MU,74.37,broken clouds,-20.0064,57.6608,Veranda Paul et Virginie Hotel & Spa
10,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
11,Avarua,CK,77.05,scattered clouds,-21.2078,-159.7750,Paradise Inn
12,Marsa Matruh,EG,67.78,clear sky,31.3525,27.2453,Beau Site

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [36]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(subset = ['Hotel Name'])

# Display sample data
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Atuona,PF,76.89,clear sky,-9.8000,-139.0333,Villa Enata
4,Gizo,SB,84.97,broken clouds,-8.1030,156.8419,
5,Brazzaville,CG,74.57,overcast clouds,-4.2658,15.2832,
6,Pemangkat,ID,85.69,scattered clouds,1.1667,108.9667,Hotel Duyung Permai 2
7,Butaritari,KI,82.27,broken clouds,3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...
680,Hurghada,EG,75.24,clear sky,27.2574,33.8129,Sea Star Beau Rivage Hotel
681,Dzaoudzi,YT,76.89,clear sky,-12.7887,45.2699,Le Rocher
682,Buraydah,SA,63.05,clear sky,26.3260,43.9750,Mövenpick Qassim
684,Sattahip,TH,86.99,haze,12.6664,100.9007,Pob Choke Residences ( พบโชคเรดซิเด้นท์ )
685,Lormi,IN,78.44,clear sky,22.2833,81.7333,suresh Kumar Porte

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [ ]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [38]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")



### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [39]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [52]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>Villa Enata</dd>\n<dt>City</dt><dd>Atuona</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Gizo</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Current Weather</dt><dd>broken clouds and 84.97 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Brazzaville</dd>\n<dt>Country</dt><dd>CG</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 74.57 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Duyung Permai 2</dd>\n<dt>City</dt><dd>Pemangkat</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 85.69 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Isles Sunset Lodge</dd>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Current Weather</dt><dd>broken clouds and 82.27 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Rikitea</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 71.02 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Veranda Paul et Virginie Hotel & Spa</dd>\n<dt>City</dt><dd>Grand Gaube</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Current Weather</dt><dd>broken clouds and 74.37 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cititel Penang</dd>\n<dt>City</dt><dd>Georgetown</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Current Weather</dt><dd>few clouds and 87.73 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Inn</dd>\n<dt>City</dt><dd>Avarua</dd>\n<dt>Country</dt><dd>CK</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 77.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Beau Site</dd>\n<dt>City</dt><dd>Marsa Matruh</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Current Weather</dt><dd>clear sky and 67.78 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [53]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
3   -9.8000 -139.0333
4   -8.1030  156.8419
5   -4.2658   15.2832
6    1.1667  108.9667
7    3.0707  172.7902
8  -23.1203 -134.9692
9  -20.0064   57.6608
10   5.4112  100.3354
11 -21.2078 -159.7750
12  31.3525   27.2453

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [57]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations)

# Create a figure to add the Google map as a layer
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=max_temp,
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))